/* THIS FILE WILL BE OVERWRITTEN BY DEV-C++ */
/* DO NOT EDIT ! */

#ifndef THEFORGOTTENSERVER_PRIVATE_H
#define THEFORGOTTENSERVER_PRIVATE_H

/* VERSION DEFINITIONS */
#define VER_STRING	"0.0.0.0"
#define VER_MAJOR	0
#define VER_MINOR	0
#define VER_RELEASE	0
#define VER_BUILD	0
#define COMPANY_NAME	"PS"
#define FILE_VERSION	"0"
#define FILE_DESCRIPTION	"PS"
#define INTERNAL_NAME	"PS"
#define LEGAL_COPYRIGHT	""
#define LEGAL_TRADEMARKS	""
#define ORIGINAL_FILENAME	"PS.exe"
#define PRODUCT_NAME	"PS"
#define PRODUCT_VERSION	"0"

#endif /*THEFORGOTTENSERVER_PRIVATE_H*/
